### ISSUE TITLE
Source parameter doesn't work

### ISSUE THREAD

**Issue by krzysztofbukowski** [premkumaranand/csv-concat#2]
When running the cli tool I'm getting the following error
<pre>
node csv-concat-cli.js -s csv -d napa.csv -p true
Fatal error merging files: Error: ENOENT: no such file or directory, stat 'c'
</pre>.

Apparently the csv concat tool expects the src to be an array, but the argument passed in CLI is a string. It takes individual letters of the src parameter value and tries to run stat on each.

**Comment by premkumaranand** [comment]
Fixed in PR #3
